- name: install Client Packages
  apt:
    name: "{{ nfs_client_packages }}"
    state: present
  tags:
    - install

- name: ensure mount directory exists
  file:
    path: "{{ client_mount_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0777
  tags:
    - configure

- name: mount the server dir
  mount:
    path: "{{ client_mount_dir }}"
    src: "{{ master_ip }}:{{ server_mount_dir }}"
    fstype: nfs
    opts: rw
    state: mounted
