- name: install Server Packages
  apt:
    name: "{{ nfs_server_packages }}"
    state: present
  tags:
    - install

- name: ensure mount directory exists
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0777
  with_items: "{{ mount_dir }}"
  tags:
    - configure

- name: update /etc/exports
  lineinfile:
    path: /etc/exports
    insertafter: EOF
    line: "{{ item }} *(rw,sync,no_subtree_check,all_squash,anonuid=0,anongid=0)"
  with_items: "{{ mount_dir }}"
  tags:
    - configure

- name: reload NFS daemon
  shell: exportfs -ar
  tags:
    - configure

- name: enable NFS services at boot
  shell: |
    systemctl enable rpcbind
    systemctl enable nfs-kernel-server
  tags:
    - configure
