- name: install Client Packages
  apt:
    name: "{{ nfs_client_packages }}"
    state: present
  tags:
    - install

- name: ensure mount directory exists
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0777
  with_items: "{{ mount_dir }}"
  tags:
    - configure

- name: mount the server dir
  mount:
    path: "{{ item }}"
    src: "{{ master_ip }}:{{ item }}"
    fstype: nfs
    opts: rw
    state: mounted
  with_items: "{{ mount_dir }}"
