apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: k8s-lb
      protocol: layer2
      addresses:
      - 192.168.60.170-192.168.60.179
