- name: Discover swap status
  shell: cat /proc/swaps | wc -l
  register: swap_out

- name: Register swap status
  set_fact:
    swap_enabled: swap_out.stdout != "1"

- name: Disable swap if enabled
  shell: |
    dphys-swapfile swapoff
    dphys-swapfile uninstall
    update-rc.d dphys-swapfile remove
  when: swap_enabled

- name: Enable memory cgroup
  lineinfile:
    path: /boot/cmdline.txt
    regexp: '^dwc(.*)$'
    line: 'cgroup_enable=memory cgroup_memory=1 dwc\1'
    backrefs: yes

- name: Reboot host
  shell: sleep 2 && /sbin/shutdown -r now "Ansible reboot"
  async: 1
  poll: 0

- name: Wait for host to come back up
  become: false
  wait_for_connection:
    delay: 15
    sleep: 2
    timeout: 120
