---
- name: generate a token beforehand
  command: kubeadm token generate
  register: token

- name: set token
  set_fact:
    token: "{{ token.stdout }}"

- name: init the cluster
  command: kubeadm init --token {{ token }} --apiserver-advertise-address={{ node_ip }} {{ cni_init_extra[cni] }}
  register: init_out

- debug: var=init_out

- name: ensure the .kube dir exists for root
  file:
    path: /root/.kube
    state: directory
    owner: root
    group: root

- name: copy in the kubernetes config to the root user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
    owner: root
    group: root

- name: ensure the .kube dir exists for pi
  file:
    path: /home/pi/.kube
    state: directory
    owner: pi
    group: pi

- name: copy in the kubernetes config to the pi user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/pi/.kube/config
    remote_src: yes
    owner: pi
    group: pi

- name: apply the CNI
  include_tasks: "cni/{{ cni }}.yml"
  when: cni is defined and cni != ''
