---
# Once https://github.com/kubernetes/kubeadm/issues/659 is resolved we can drop the unsafe flag and get/use the hash
<<<<<<< HEAD
- name: join the cluster | {{join_cmd}}
  command: "{{ join_cmd }}"
=======
- name: join the cluster
  command: {{ join_cmd }}
>>>>>>> 6574f80c3d9a7591258ca454f9fd617cf1769fc2
  register: out

- name: print stdout
  debug:
    var: out
