---
- name: generate a new join command expiring in 15 mins
  shell: kubeadm token create --print-join-command --ttl 15m
  register: join_cmd_out

- name: set the current join cmd
  set_fact:
    join_cmd: "{{ join_cmd_out.stdout }}"
