---
- name: install k8s
  include_tasks: install.yml
  tags:
    - install
    - upgrade

- name: configure OS
  include_tasks: configure_os.yml
  tags:
    - install

- name: discover node status
  include_tasks: discover.yml

- debug: var=node
- debug: var=cluster

- name: create the cluster
  include_tasks: init.yml
  when:
    - node == "master"
    - cluster != "initialized"
  tags:
    - init

- name: set the master information
  set_fact:
    token: "{{ hostvars['node00'].token }}"  # Need to be set after discovery/init

- debug: var=node_ip
- debug:
    var: master_ip
  when:
    - node == "slave"
- debug: var=token

- name: join the cluster
  include_tasks: join.yml
  when:
    - node == "slave"
    - cluster != "joined"
    - token is defined and token != ""
    - master_ip is defined and master_ip != ""
  tags:
    - join

- name: discover node status again once everyone has joined
  include_tasks: discover.yml

- name: show cluster status
  shell: kubectl get nodes
  register: nodes_out
  when:
    - node == "master"

- debug: var=nodes_out
