---
kube_version: "1.13.1-00"

k8s_packages:
- "kubeadm"
- "kubectl"
- "kubelet"

package_versions:
  kubeadm: "{{ kube_version }}"
  kubectl: "{{ kube_version }}"
  kubelet: "{{ kube_version }}"

reset: false
cluster: ""

master_port: 6443

cni: "flannel"

cni_init_extra:
  flannel: "--pod-network-cidr=10.244.0.0/16"
  weave: ""
