---
- name: change hostname to match node name
  hostname:
    name: "{{ inventory_hostname }}"

- name: update /etc/hosts as well
  lineinfile:
    path: /etc/hosts
    regexp: "^127.0.1.1\t.*$"
    line: "127.0.1.1\t{{ inventory_hostname }}"

- name: update apt repos
  apt:
    update_cache: yes

- name: install common packages
  apt:
    name: "{{ common_packages }}"
    state: present
